config/routes.rb
Rails.application.routes.draw do

root to: "home#index"
resources :users
resources :timecards do
  resources :days
  end
resources :days

# get "/log-in" => "sessions#new"
# post "/log-in" => "sessions#create"
# delete "/log-out" => "sessions#destroy"
resources :sessions, only: [:new, :create, :destroy]

end

app/models/day.rb
class Day < ActiveRecord::Base

  belongs_to :timecard
  belongs_to :user

  validates :work_date, presence: true
  validates :start_time, presence: true
  validates :stop_time, presence: true
  validates :lunch_start, presence: true
  validates :lunch_end, presence: true

validate :verify_date

  def total_lunch
    (lunch_end - lunch_start) / 3600 
  end

  def total_hours
    (stop_time - start_time) / 3600
  end

  def total_day
    total_hours - total_lunch
  end

    def verify_date
    if self.work_date != nil && self.work_date < self.timecard.start_date
      errors.add(:interview_date, "must be during timecard week")
      return false
    end
  end


end

app/models/timecard.rb
class Timecard < ActiveRecord::Base

  belongs_to :user
  has_many :days, ->{ order("work_date DESC") }, dependent: :destroy

  accepts_nested_attributes_for :days, :reject_if => :all_blank

  validates :start_date, presence: true
  validates :end_date, presence: true

  scope :order_by_newest, ->{ order("start_date DESC") }
  scope :order_by_oldest, ->{ order("start_date ASC") }
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password

  has_many :timecards
  has_many :days

  # has_secure_password

  # before_save { self.email = email.downcase if self.email }
  before_save :encrypt_password

  # EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # validates :name, presence: true, length: { maximum: 60 }
  validates :email, presence: true, uniqueness: true, :format => { :with => /@/, :message => "Invalid email format" }
  # format: { with: EMAIL_REGEX },
  #   uniqueness: true, length: { minimum: 6 }
  # # validates :password, length: { minimum: 8 }
  validates_confirmation_of :password

def self.authenticate(email, password)
  user = User.where(email: email).first
  if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
  user
  else
  nil
  end
  # user = find_by_email(email)
  # if user && user.authenticate(password)
  #   user
  # else
  #   nil
  # end
end

def encrypt_password
  self.password_salt = BCrypt::Engine.generate_salt
  self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_filter :find_timecard
  before_filter :find_day, except:[:index,:new,:create]
  
  respond_to :html, :js

  def new
    @day = @timecard.days.new
  end

  def create
    @day = @timecard.days.create(day_params)
  end

  def edit
  end

  def update
    if @day.update(day_params)
      redirect_to timecard_path(@timecard), notice: "Updated Successfully"
    else
      render 'edit', alert:"Failed to Update"
    end
  end

  def show
  end

  def destroy
    @day.destroy
    flash["notice"]="Day Removed"
  end

private

  def day_params
    params.require(:day).permit(:work_date, :start_time, :stop_time, :lunch_start, :lunch_end, :user_id, :timecard_id)
  end

  def find_day
    @day = Day.find(params[:id])
  end

  def find_timecard
    @timecard = Timecard.find(params[:timecard_id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
  @timecards = Timecard.all
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.authenticate(params[:session][:email], params[:session][:password])
    if @user
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged in as #{@user.email}"
    else
      redirect_to new_session_path, alert: "Name or Password is Invalid"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signing Out Successfully"
  end

end

app/controllers/timecards_controller.rb
class TimecardsController < ApplicationController
  before_filter :find_timecard, except: [:index,:new,:create]

  respond_to :html, :js

  def index
    @timecards = Timecard.all.where(user_id:current_user.id).order_by_newest
  end

  def new
    @timecard = Timecard.new
  end

  def create
    @timecard = Timecard.create(timecard_params)
    @timecards = Timecard.all.where(user_id:current_user.id).order_by_newest
  end

  def show
    @day = @timecard.days.new
  end

  def edit
  end

  def update
    @timecard.update(timecard_params)
    @day = @timecard.days.new
  end

  def destroy
    @timecard.destroy
    redirect_to root_url
    flash["notice"]="Destroyed Successfully"
  end

private
  
  def timecard_params
    params.require(:timecard).permit(:start_date, :end_date, :user_id, day_attributes:[:start_time, :stop_time, :lunch_start, :lunch_stop])
  end

  def find_timecard
    @timecard = Timecard.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Created Account for #{@user.name}"
    else
      render 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to root_url, notice: "Updated Successfully"
    else
      render 'edit', notice: "Failed to Update"
    end
  end



private

  def user_params
    params.require(:user).permit(:name, :email, :phone, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def users_name
    if current_user.name
      return current_user.name
    else
      return current_user.email
    end
  end

end

app/views/days/_form.html.erb
<%= form_for(([@timecard, @day]), remote: true, html: {class: 'form-horizontal' }) do |f| %>
  <%= render 'layouts/errors', object: @day %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="form-group">
    <%= f.label :work_date, "Day Worked", class: "col-xs-12 col-sm-2"%>
    <div class="input-group col-xs-8 col-sm-2">
      <span class="input-group-addon"><i class="fa fa-calendar fa-fw"></i></span>
      <%= f.date_field :work_date, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :start_time, "Start Time", class: "col-xs-12 col-sm-2"%>
    <div class="input-group col-xs-8 col-sm-2">
      <span class="input-group-addon"><i class="fa fa-clock-o fa-fw"></i></span>
      <%= f.time_field :start_time, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :stop_time, "Stop Time", class: "col-xs-12 col-sm-2"%>
    <div class="input-group col-xs-8 col-sm-2">
      <span class="input-group-addon"><i class="fa fa-clock-o fa-fw"></i></span>
      <%= f.time_field :stop_time, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :lunch_start, "Lunch Started", class: "col-xs-12 col-sm-2"%>
    <div class="input-group col-xs-8 col-sm-2">
      <span class="input-group-addon"><i class="fa fa-clock-o fa-fw"></i></span>
      <%= f.time_field :lunch_start, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :lunch_end, "Lunch Ended", class: "col-xs-12 col-sm-2"%>
    <div class="input-group col-xs-8 col-sm-2">
      <span class="input-group-addon"><i class="fa fa-clock-o fa-fw"></i></span>
      <%= f.time_field :lunch_end, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="offset3 col-sm-offset-2 col-sm-3">
      <%= render 'layouts/submit', form_type: "Day", object: @day, f: f %>
    </div>
  </div>
<% end %>

app/views/days/create.js.erb
$("#show-ajax").html("<%= escape_javascript(render 'timecards/show') %>")
$('#view-workday-icon-change').toggleClass('fa-chevron-up').toggleClass('fa-chevron-down');
$('#view-workdays').slideToggle();

app/views/days/index.html.erb
<h1>Timecards</h1>

<p><strong>Timecard Start Date: </strong><%= @timecard.start_date %></p>

<% @days.each do |day| %>
  <%= link_to "<p><strong>Timecard Start Date:</strong></p> #{day.start_time}".html_safe, day__path(day) %>
<% end %>

app/views/days/new.js.erb
// $("#add-workday").html("<%= escape_javascript(render 'days/form') %>")
$("#add-workday").show();

app/views/days/show.html.erb
<h1><%= @timecard.day %></h1>

<p>Timecard Day details</p>

<%= @day.start_time %>
<%= @day.stop_time %>
<%= @day.lunch_start %>
<%= @day.lunch.stop %>

<%= link_to "Update Day Details", day_path(@day) %>

app/views/home/index.html.erb
<div class="container-fluid">

  <div class="jumbotron jumbo">
    <h1>Welcome to Timeclok
    <%= image_tag("time-icon.png", class:"home-time") %>
    </h1>

    <% if current_user %>
      <h3>Hello <%= link_to "#{users_name}", edit_user_path(current_user), class: "edit-user" %>
      <%= link_to "<i class='fa fa-sign-out fa-fw'></i>Logout".html_safe, session_path(session), class: "btn btn-default btn-lg", data: {method: :delete}, title:"Logout" %>
      </h3>
    <% else %>
      <%= link_to '<i class="fa fa-plus fa-fw"></i> Create a New Account'.html_safe, new_user_path, class: "btn btn-default" %>
      <%= link_to '<i class="fa fa-sign-in fa-fw"></i> Log In'.html_safe, new_session_path, class: "btn btn-default" %>
    <% end %>
  </div>


  <div class="row1">
    <div class="col-xs-12 col-sm-6 clearfix">
      <%= link_to "<i class='fa fa-archive'></i> Manage Timecards".html_safe, timecards_path, class: "btn btn-default float-btn btn-lg", title: "View and Manage all timecards" if current_user %>
      <%= link_to '<i class="fa fa-plus fa-fw"></i> Edit Profile'.html_safe, edit_user_path(current_user), class: "btn btn-default float-btn btn-lg", title: "Edit profile settings" if current_user %>
    </div>
    <div class="col-xs-12 col-sm-6">
      <p>Create timecards for a specified time period. Then you can add days to the timecard. On each day you can enter a start time, stop time, lunch start time, and lunch stop time.</p>
    </div>
  </div>
  <div class="row2"></div>

</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <div class="error_explanation">
      <h4><%= pluralize(object.errors.count, "error") %> prohibited this activity from being saved:</h4>

      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/_flash.html.erb
<div id="flash" class="clearfix">
  <% if flash[:notice] != nil %>
    <div class='alert alert-success' role='alert'>
      <%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] != nil %>
    <div class='alert alert-danger' role='alert'>
      <%= flash[:alert] %></div>
  <% end %>
</div>

app/views/layouts/_login.html.erb
<% if user_signed_in? %>
  
  <li class="dropdown">
    <%= link_to "#{current_user.username} <b class='caret'></b>".html_safe, "#", class: "dropdown-toggle", data: {toggle: "dropdown"} %>
    <ul class="dropdown-menu">
      <li>
        <%= link_to edit_user_registration_path do %>
          <i class="fa fa-pencil fa-fw"></i>
          Edit Profile
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out fa-fw"></i>
          Log Out
        <% end %>
      </li>
    </ul>
  </li>

<% else %>

  <li class="dropdown">
    <%= link_to "Log In or Create Account <b class='caret'></b>".html_safe, "#", class: "dropdown-toggle", data: {toggle: "dropdown"} %>
    <ul class="dropdown-menu">
      <li>
        <%= link_to new_user_registration_path do %>
          <i class="fa fa-plus-circle fa-fw"></i>
          Create Account
        <% end %>
      </li>
      <li>
        <%= link_to new_user_session_path do %>
          <i class="fa fa-sign-in fa-fw"></i>
          Log In
        <% end %>
      </li>
    </ul>
  </li>
  
<% end %>

app/views/layouts/_password.html.erb
  <div class="form-group">
    <%= f.label :password, "Password", class: "col-sm-4 control-label" %>
    <div class="input-group col-sm-7">
      <span class="input-group-addon"><i class="fa fa-key fa-fw form-fa"></i></span>
      <%= f.password_field :password, required: true, :placeholder => 'Password with 8 characters', class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, "Confirm Password:", class: "col-sm-4 control-label" %>
    <div class="input-group col-sm-7">  
      <span class="input-group-addon"><i class="fa fa-key fa-fw form-fa"></i></span>
      <%= f.password_field :password_confirmation, required: true, :placeholder => 'Type it again to confirm', class: "form-control"  %>
    </div>
  </div>

app/views/layouts/_submit.html.erb
<%= button_tag(type: "submit", class: "btn btn-default btn-lg float-btn", title: f.object.new_record? ? "<i class='fa fa-plus-circle fa-fw'></i>Create ".html_safe + form_type : "<i class='fa fa-plus-circle fa-fw'></i>Update ".html_safe + form_type) do %>
  
  <%= f.object.new_record? ? "Create " + form_type : "Update " + form_type %>
<% end %>

<% if @day %>
  <%= link_to "<i class='fa fa-arrow-circle-left fa-fw'></i> Cancel".html_safe, timecard_path(@timecard), class: "btn btn-default btn-lg float-btn",title:"Cancel" %>  
<% else %>
  <%= link_to "<i class='fa fa-arrow-circle-left fa-fw'></i> Cancel".html_safe, root_path, class: "btn btn-default btn-lg float-btn",title:"Cancel" %>
<% end %>

app/views/layouts/_username.html.erb
<% if current_user.name %>
  <span class="username-style"><%= current_user.name %></span>
<% else %>
  <span class="username-style"><%= current_user.email %></span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timeclok</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="yield-box">
    <%= render 'layouts/flash' %>
    <%= yield %>
  </div>

</body>
</html>

app/views/timecards/_create.js.erb
console.log("nacho")
$("#timecard-new").hide();

app/views/timecards/_edit.html.erb
<% content_for(:title, "Update Timecard") %>

<div class="border-form-div">
  <h2>Update Timecard Details</h2>
  <%= render 'form' %>
</div>

app/views/timecards/_form.html.erb
<%= form_for(@timecard, remote: true, html: { class: 'form-horizontal' }) do |f| %>
    <ul class="errors"></ul>
    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="form-group">
      <%= f.label :start_date, "Start Date", class: "control-label" %>
      <%= f.date_field :start_date, class:"form-control" %>
    </div>

    <div class="form-group">
    <%= f.label :end_date, "End Date", class: "control-label" %>
    <%= f.date_field :end_date, class:"form-control" %>
    </div>



    <div class="form-group">
      <div class="offset3 col-sm-offset-3 col-sm-6">
        <%= render 'layouts/submit', form_type: "Timecard", object: @timecard, f: f %>
      </div>
    </div>


<% end %>

app/views/timecards/_index.html.erb
<% @timecards.each do |timecard| %>
      <p><strong><i class="fa fa-clock-o"></i> Timecard Date: </strong><%= link_to "#{timecard.start_date.strftime("%m/%d/%Y")} - #{timecard.end_date.strftime("%m/%d/%Y")}", timecard_path(timecard) %> </p>
<% end %>

app/views/timecards/_new.html.erb
<% content_for(:title, "Create New Timecard") %>

<div class="border-form-div">
  <h2>Enter Timecard Details</h2>
  <%= render 'form' %>
</div>

app/views/timecards/_show.html.erb
<div class="jumbotron jumbo">
  <h2 class="row-head">Timecard Detail</h2>
  <%= link_to "<i class='fa fa-archive'></i> View All Timecards".html_safe, timecards_path, class: "btn btn-default btn-lg" %>
</div>

<div class="row1">
  <h3 class="row-head">Work Week</h3>
  <p><i class='fa fa-calendar'></i> <%= link_to "#{@timecard.start_date.strftime('%m/%d/%Y')} - #{@timecard.end_date.strftime('%m/%d/%Y')}".html_safe, edit_timecard_path(@timecard), remote: true %></p>
  <div id="timecard-edit">
  </div>
  <%= link_to "Add a Workday <i id='add-workday-icon-change' class='fa fa-chevron-down'></i>".html_safe, new_timecard_day_path(@timecard, @day), remote: true, id:"add-workday-btn",class: "btn btn-default btn-lg",title:'Click if you want to to add workday details' %>
  <%= button_tag("View Timecard Days <i id='view-workday-icon-change' class='fa fa-chevron-down'></i>".html_safe, id:"view-workdays-btn",type:'button',class: "btn btn-default btn-lg",title:'Click if you want to to view the days for this timecard') %>
  <%= button_tag("View Timecard Summary <i id='view-timecard-summary-icon-change' class='fa fa-chevron-down'></i>".html_safe, id:"view-timecard-summary-btn",type:'button',class: "btn btn-default btn-lg",title:'Click if you want to to view the timecard summary for the week') %>
</div>

<div class="row2">
  <div id="add-workday">
    <%= render 'days/form' %>
  </div>
</div>

<div class="row3">
  <div id="view-workdays">
    <%= render 'timecards/days_worked' %>
  </div>
</div>  

<div class="row4">
  <div id="view-timecard-summary">
    <%= render 'timecards/week_worked' %>
  </div>
</div>

app/views/timecards/_update.html.erb
$("ul.errors").html("")
<% if @timecard.errors.any? %>
  <% @timecard.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $("#show-ajax").html("<%= escape_javascript(render 'show') %>")
  $("#timecard-edit").toggle();
<% end %>

app/views/timecards/_week_worked.html.erb
<div class="col-xs-12 col-sm-6">
  <h4 class="row-head">Week Summary</h4>
    <table class="table table-condensed table-bordered table-striped">
      <thead>
        <th colspan="4"><i class="fa fa-calendar"></i><strong> Work Week Summary: </strong></th>
      </thead>
      <tbody>
        <tr>
          <td><strong>Day: </strong></td>
          <td><strong>Hours Worked: </strong></td>
          <td><strong>Lunch: </strong></td>
          <td><strong>Total: </strong></td>
        </tr>
        <% @total_week =0 %>
        <% @timecard.days.each do |day| %>
          <% if day.work_date != nil %>
          <% @total_week = @total_week + day.total_hours - day.total_lunch %>
            <tr>
              <td><%= day.work_date.strftime("%m/%d/%Y") %></td>    
              <td><%= day.total_hours %></td>
              <td><%= day.total_lunch %> hrs</td>
              <td><%= day.total_hours - day.total_lunch %> hrs</td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
      <tfoot>
        <th colspan="4"><strong><i class="fa fa-calculator fa-fw "></i>Total Hours Worked for Week: </strong><%= @total_week %> hrs</th>
      </tfoot>
    </table>

</div>

app/views/timecards/edit.js.erb
$("#timecard-edit").html("<%= escape_javascript(render 'edit') %>")
$("#timecard-edit").show();

app/views/timecards/index.html.erb
<div class="container-fluid">

  <div class="jumbotron jumbo">
    <h2>Timecards
    <%= image_tag("time-icon.png", class:"home-time") %>
    </h2>
  <p>Account: <%= render 'layouts/username' %></p>
  <%= link_to '<i class="fa fa-plus-circle"></i> Create New Timecard'.html_safe, new_timecard_path, remote: true, class:"btn btn-lg btn-default" %>
  <%= link_to '<i class="fa fa-home"></i> Home'.html_safe, root_url, class: "btn btn-lg btn-default" %>
  </div>

  <div class="timecard-index">
    <%= render 'index' %>
  </div>

<div id="timecard-new">
</div>

</div>

app/views/timecards/new.html.erb
<% content_for(:title, "Create New Timecard") %>

<div class="border-form-div">
  <h2>Enter Timecard Details</h2>
  <%= render 'form' %>
</div>

app/views/timecards/new.js.erb
$("#timecard-new").html("<%= escape_javascript(render 'new') %>")
$("#timecard-new").show();

app/views/timecards/show.html.erb
<div class="container-fluid" id="show-ajax">
  <%= render 'show' %>
</div>

app/views/timecards/update.js.erb
<%= render 'update' %>

app/views/users/_form.html.erb
<%= form_for @user, url_path: users_path do |f| %>
  <%= render 'layouts/errors', object: @user %>

  <div class="form-group">
    <%= f.label :email, "Email", class: "col-sm-4 control-label" %>
    <div class="input-group col-sm-7">
      <span class="input-group-addon"><i class="fa fa-envelope-o fa-fw form-fa"></i></span>
      <%= f.email_field :email, required: true, autofocus: true, :placeholder => 'email@provider.com', class: "form-control"  %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :name, "Full Name", class: "col-sm-4 control-label" %>
    <div class="input-group col-sm-7">
      <span class="input-group-addon"><i class="fa fa-user fa-fw form-fa"></i></span>
      <%= f.text_field :name, :placeholder => 'Enter Full Name', class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :phone, "Phone", class: "col-sm-4 control-label" %>
    <div class="input-group col-sm-7">
      <span class="input-group-addon"><i class="fa fa-phone fa-fw form-fa"></i></span>
      <%= f.phone_field :phone, :placeholder => 'ie. 123-45-6789', class: "form-control"  %>
    </div>
  </div>
  <%= render 'layouts/password', f:f %>

  <div class="form-group">
    <div class="offset3 col-sm-offset-4 col-sm-9">
      <%= render 'layouts/submit', form_type: "User", object: @user, f: f %>
      <%= link_to '<i class="fa fa-sign-in fa-fw"></i> Log In'.html_safe, new_session_path, class: "btn btn-default" if !current_user %>
    </div>
  </div>
  
<% end %>

app/views/users/edit.html.erb
<% content_for(:title, "Update User") %>

<div class="border-form-div">
  <h2>Update Your Account</h2>
  <%= render 'form' %>
</div>

app/views/users/new.html.erb
<% content_for(:title, "Create User") %>

<div class="border-form-div">
  <h2>Create New Account</h2>
  <%= render 'form' %>
</div>